export const SWITCH_MONTH_NEXT = 'SWITCH_MONTH_NEXT';
export const SWITCH_MONTH_PREVIOUS = 'SWITCH_MONTH_PREVIOUS';
export const SELECT_DAY = 'SELECT_DAY';
export const SUBMIT_APPOINTMENT = 'SUBMIT_APPOINTMENT';
export const CLEAR_APPOINTMENT = 'CLEAR_APPOINTMENT';
